### ISSUE TITLE
Calling a function version

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/rir#57] opened 2017-10-12 19:52 UTC
# Current status

In #49 and #54, we added function dispatch tables. When a function is optimized, the new version is inserted into the dispatch table, at the end. The baseline version is always the first entry of the table. Currently, functions are only optimized once, so a dispatch table will contain at most two entries.

By default, calling a function will pick the first entry. There is currently no way to call the optimized version. (This was to keep the implementation simpler and avoid having to deoptimize.)

This brings us to the next step: how do we call a different function version? How do we update a caller so that it calls a different version of the callee? We could generate a new version of the caller, but then it's caller also needs to be updated. We could update code in place, but that will get messy, and might not always be possible (e.g. what if we change the calling convention of the callee).

# Proposal

In our discussion, we decided that each entry in the dispatch table represents some signature/interface/set of assumptions.

The compiler is free to change the contents of an entry to a new version, as long as that version satisfies the interface. (We could even consider a "subtyping" relation between two interfaces.) This way, when we optimize a function, we can just update the corresponding entry in the dispatch table, without updating the caller code. The same goes for deoptimizing: we just update the entry in the table.

(If we want to change the calling convention of a function, we have to update the caller code, e.g. to pass arguments on the stack. At the same time, we can update the call so it selects a different entry from the dispatch table.)

## Changing a table entry

We'll store all the existing function versions somewhere, e.g. a linked list. And each function will have a pointer to its baseline version.

So when we optimize a function, the compiler generates a new version, adds it to the linked list, and updates the corresponding entry. The new version also has a pointer to its baseline version.

When we deoptimize, we follow the pointer to the baseline version, and insert that back into the dispatch table.

**Question: Is this a reasonable approach? ~~It's very similar to what we had previously (follow the `origin` pointer), but would we still be hit by #7~~?**

**Question: Where do we store the linked list of functions? How do we get the GC to trace it? Do we want to remove versions and let them be collected?**

  1. We could keep a pointer to the linked list in the header of the dispatch table. This keeps the linked list separate from the dispatch table, and it's easy to remove versions. However, tracing through it with the GC is hard.

  2. We store them in the same array as the dispatch table. So the first portion is the dispatch table, and the second portion is the list (well, array now) of all the function versions. This is easy for the GC to handle, but it'll be tricky to implement. And from a maintenance/readability perspective, this approach is a bit convoluted.

## Function signatures

We need some way of specifying the signature/interface/assumptions for a function version. This signature will be recorded in the function metadata, and will also be referenced by a call instruction. That way, a call will know which table entry to look up. (Later, we can update the code in place to record the offset of the entry.)

As a start, we'll probably want to record three dimensions of information: type (e.g. integer, scalar, vector), evaluation (promise or not promise), and position (stack position or argument list).

**Question: What specifically do we want to record in the signature? What does it look like?**

Seems like it would be an array, where each element is a structure recording the type, evaluation, and position information.

For types, we could just use the [sexptypes](https://github.com/reactorlabs/gnur/blob/rir-patch-3-3-branch/src/include/Rinternals.h#L114). This would require 4 bytes to represent, but we could significantly reduce that if we only numbered the sexptypes we care about. (As a guess, we probably care about less than 8 different types.)

For evaluation, we just need a single bit for promise/not promise.

For position, we need an integer for the stack position. If the argument is in the linked list, we don't care about its position in the list.

**Question: Where do we put the signature?**

In JVM bytecode, method signatures are stored in the constant pool, so they only need to be allocated once. Each method has an index into the constant pool, and call instructions provide an index into the constant pool, to refer to the signature.

I think we should do something similar, because the signature can get pretty large (and is basically unbounded).

**Comment by o-** [comment] 2017-10-13 10:02
## Changing a table entry

> Question: Is this a reasonable approach? 

sure.

> It's very similar to what we had previously (follow the origin pointer), but would we still be hit by #7?

The two things are unrelated. #7 is a problem of the optimizer, that does not properly update the deoptimization metadata. We can solve this problem separately (I can work on that)...

But yeah, indeed we basically keep what we have now :)

> Question: Where do we store the linked list of functions? 

Well, the first function is in the dispatch table, and the rest are reachable through that first function, not? since we only add functions to the top, that should be easy to maintain. (basically like it is now :)

> How do we get the GC to trace it?

Well, expose the "next" pointer of the functions to the GC (same trick as in the dispatch table).

> Do we want to remove versions and let them be collected?

maybe, we don't have to decide now...

> We could keep a pointer to the linked list in the header of the dispatch table. 

remember, there needs to be one list per signature. also, not necessary. The functions are the linked list (they point to the previous function). Thus first function in the dispatch table is good enough.

> Question: Where do we store the linked list of functions? How do we get the GC to trace it? Do we want to remove versions and let them be collected?

imho, inline in the function object and add a gc traceable section to the function (like in the dispatch table) and store next pointer there.

## Function signatures

> Question: What specifically do we want to record in the signature? What does it look like?
> 
> Seems like it would be an array, where each element is a structure recording the type, evaluation, and position information.

An array is bad (since equality is slow).
why not just an integer (bitfield)?

**Comment by mhyee** [comment] 2017-10-13 18:07
Hmm, in the last call, I was under the impression that all the versions for a function would be in a single linked list. But having one linked list per signature seems it'd be easier to implement. We should discuss this in our next call.

> An array is bad (since equality is slow).
why not just an integer (bitfield)?

Sure, we could play the bit packing game.

And if we store signatures in the constant pool, then equality is just comparing pointers, so it's still fast.

**Comment by o-** [comment] 2020-01-22 12:05
this is still ongoing but the issue is not really used to track progress, so closing

**Closed as completed by o-** 2020-01-22 12:05 UTC
Labels: research
